spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
camunda.bpm.admin-user:
  id: demo
  password: demo1

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://financemysqlserverbackup1.mysql.database.azure.com:3306/financeDatabase
    username: financeapp
    password: mysql@123